name: Publish package

on:
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    if: github.repository == 'atlasisles/adventure-kt'

    steps:
      - uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
      - name: Make gradlew executable
        run: chmod +x ./gradlew
      - name: Publish package
        run: ./gradlew publish
        env:
          ORG_GRADLE_PROJECT_atlasislesReleasesUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_atlasislesReleasesPassword: ${{ secrets.MAVEN_PASSWORD }}
          ORG_GRADLE_PROJECT_atlasislesSnapshotsUsername: ${{ secrets.MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_atlasislesSnapshotsPassword: ${{ secrets.MAVEN_PASSWORD }}